#
# rm-macl/lib/rm-macl/xpan/surface/constants.rb
#
require 'rm-macl/macl-core'
module MACL
  class Surface

    ##
    # anchors (2D)
    ANCHOR_NONE          = 0x200

    ANCHOR_TOP           = ANCHOR_NONE | 0x10
    ANCHOR_MIDDLE        = ANCHOR_NONE | 0x20
    ANCHOR_BOTTOM        = ANCHOR_NONE | 0x30

    ANCHOR_LEFT          = ANCHOR_NONE | 0x01
    ANCHOR_CENTER        = ANCHOR_NONE | 0x02
    ANCHOR_RIGHT         = ANCHOR_NONE | 0x03

    ANCHOR_TOP_LEFT      = ANCHOR_TOP | ANCHOR_LEFT
    ANCHOR_TOP_CENTER    = ANCHOR_TOP | ANCHOR_CENTER
    ANCHOR_TOP_RIGHT     = ANCHOR_TOP | ANCHOR_RIGHT

    ANCHOR_MIDDLE_LEFT   = ANCHOR_MIDDLE | ANCHOR_LEFT
    ANCHOR_MIDDLE_CENTER = ANCHOR_MIDDLE | ANCHOR_CENTER
    ANCHOR_MIDDLE_RIGHT  = ANCHOR_MIDDLE | ANCHOR_RIGHT

    ANCHOR_BOTTOM_LEFT   = ANCHOR_BOTTOM | ANCHOR_LEFT
    ANCHOR_BOTTOM_CENTER = ANCHOR_BOTTOM | ANCHOR_CENTER
    ANCHOR_BOTTOM_RIGHT  = ANCHOR_BOTTOM | ANCHOR_RIGHT

    ##
    # NUMPAD_ANCHOR [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
    NUMPAD_ANCHOR =[ANCHOR_NONE,
                    ANCHOR_BOTTOM_LEFT, ANCHOR_BOTTOM_CENTER, ANCHOR_BOTTOM_RIGHT,
                    ANCHOR_MIDDLE_LEFT, ANCHOR_MIDDLE_CENTER, ANCHOR_MIDDLE_RIGHT,
                    ANCHOR_TOP_LEFT,    ANCHOR_TOP_CENTER,    ANCHOR_TOP_RIGHT]

    ##
    # based on the 1 num style from the original anchors
    EXTENDED_ANCHOR = {
      80 => ANCHOR_TOP,
      28 => ANCHOR_MIDDLE,
      20 => ANCHOR_BOTTOM,
      40 => ANCHOR_LEFT,
      46 => ANCHOR_CENTER,
      60 => ANCHOR_RIGHT,
    }

    # Used with Bitmap#draw_text
    ALIGN_TOP    = ALIGN_LEFT   = 0x0
    ALIGN_MIDDLE = ALIGN_CENTER = 0x1
    ALIGN_BOTTOM = ALIGN_RIGHT  = 0x2

    ## Alternative Names
    ANCHOR_N  = ANCHOR_TOP_CENTER
    ANCHOR_NE = ANCHOR_TOP_RIGHT
    ANCHOR_E  = ANCHOR_MIDDLE_RIGHT
    ANCHOR_SE = ANCHOR_BOTTOM_RIGHT
    ANCHOR_S  = ANCHOR_BOTTOM_CENTER
    ANCHOR_SW = ANCHOR_BOTTOM_LEFT
    ANCHOR_W  = ANCHOR_MIDDLE_LEFT
    ANCHOR_NW = ANCHOR_TOP_LEFT

  end
end
MACL.register('macl/xpan/surface/constants', '1.2.0')