#
# RGSS3-MACL/lib/xpan-lib/surface/constants.rb
# vr 1.0.1
module MACL
class Surface

  ##
  # anchors (2D)
  ANCHOR_NONE          = 0x200

  ANCHOR_TOP           = ANCHOR_NONE | 0x10
  ANCHOR_YCENTER       = ANCHOR_NONE | 0x20
  ANCHOR_BOTTOM        = ANCHOR_NONE | 0x30

  ANCHOR_LEFT          = ANCHOR_NONE | 0x01
  ANCHOR_XCENTER       = ANCHOR_NONE | 0x02
  ANCHOR_RIGHT         = ANCHOR_NONE | 0x03

  ANCHOR_TOP_LEFT      = ANCHOR_TOP | ANCHOR_LEFT
  ANCHOR_TOP_CENTER    = ANCHOR_TOP | ANCHOR_XCENTER
  ANCHOR_TOP_RIGHT     = ANCHOR_TOP | ANCHOR_RIGHT

  ANCHOR_CENTER_LEFT   = ANCHOR_YCENTER | ANCHOR_LEFT
  ANCHOR_CENTER        = ANCHOR_YCENTER | ANCHOR_XCENTER
  ANCHOR_CENTER_RIGHT  = ANCHOR_YCENTER | ANCHOR_RIGHT

  ANCHOR_BOTTOM_LEFT   = ANCHOR_BOTTOM | ANCHOR_LEFT
  ANCHOR_BOTTOM_RIGHT  = ANCHOR_BOTTOM | ANCHOR_RIGHT
  ANCHOR_BOTTOM_CENTER = ANCHOR_BOTTOM | ANCHOR_XCENTER

  ##
  # NUMPAD_ANCHOR
  NUMPAD_ANCHOR =[ANCHOR_NONE,
                  ANCHOR_BOTTOM_LEFT, ANCHOR_BOTTOM_CENTER, ANCHOR_BOTTOM_RIGHT,
                  ANCHOR_CENTER_LEFT,    ANCHOR_CENTER,     ANCHOR_CENTER_RIGHT,
                  ANCHOR_TOP_LEFT,    ANCHOR_TOP_CENTER,    ANCHOR_TOP_RIGHT]

  EXTENDED_ANCHOR = {
    80 => ANCHOR_TOP,
    28 => ANCHOR_YCENTER,
    20 => ANCHOR_BOTTOM,
    40 => ANCHOR_LEFT,
    46 => ANCHOR_XCENTER,
    60 => ANCHOR_RIGHT,
  }

  # Used with Bitmap#draw_text
  ALIGN_LEFT   = 0x0
  ALIGN_CENTER = 0x1
  ALIGN_RIGHT  = 0x2

end
end
