MACL.linara_add __FILE__, [
  ['archijust.rb',  0],
  ['arraytable.rb', 0],
  ['blaz.rb',       0],
  ['chitat.rb',     0],
  ['cube.rb',       0],
  ['drool.rb',      0],
  ['fifo.rb',       0],
  ['geometry.rb',   0],
  ['grid.rb',       0],
  ['interpolate.rb',0],
  ['morph.rb',      0],
  ['pallete.rb',    0],
  ['point.rb',      0],
  ['sequencer.rb',  0],
  ['surface.rb',    0],
  ['table-ex.rb',   0],
  ['task.rb',       0],
  ['tween.rb',      0]
]
